version: '3.5'
services:
  proposta-app:
    image: proposta-app
    environment:
      spring.profiles.active: prod
    depends_on:
      - rabbit-mq
      - db
    ports:
      - "8080:8080"
  rabbit-mq:
    image: rabbit:3-management
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: propostadb
